// SPDX-FileCopyrightText: 2025 Weidmueller Interface GmbH & Co. KG <oss@weidmueller.com>
//
// SPDX-License-Identifier: MIT

= u-OS Data Hub - API Specifications
:toc:

The `u-os-hub-api` repository contains API specifications for the u-OS Data Hub.

A general explanation of what the u-OS Data Hub is can be found link:https://support.weidmueller.com/online-documentation/latest/312416/en-GB/index.html#142143243146210187[here].

== Variable APIs

The u-OS Data Hub Variable APIs are compared link:https://support.weidmueller.com/online-documentation/latest/312416/en-GB/index.html#142279051[here].

=== Variable-NATS-API

In the Variable-NATS-API, link:https://nats.io/[NATS] is used as the transport mechanism.
And link:https://flatbuffers.dev/[FlatBuffers] are transmitted there as payload.

To use the Variable-NATS-API, we recommend using the link:https://github.com/weidmueller/u-os-hub-client-rs[u-os-hub-client-rs library].

Alternatively, you can create your own library by directly using flatbuffers and nats libraries for your desired language.
All NATS subjects are documented in the corresponding link:https://www.asyncapi.com/en[AsyncAPI] specification: `link:variable-nats-asyncapi.yaml[variable-nats-asyncapi.yaml]`.
The FlatBuffers messages and types are located in the `link:flatbuffers[flatbuffers]` directory.

==== Compiling FlatBuffers schemata

FlatBuffers schemata are compiled into target source code via the `flatc` compiler.
Flatc is not included in this repository, but can be downloaded from link:https://github.com/google/flatbuffers/releases[here].
For an example how to use flatc, see the link:https://flatbuffers.dev/flatc/[Flatbuffers documentation].

=== Variable-HTTP-API

We use link:https://spec.openapis.org/oas/latest.html[OpenAPI] to describe the Variable-HTTP-API in the file `variable-http-openapi.yaml`.

==== Generating a client library

You can use the OpenAPI Generator to generate client library for your desired programming language.
The OpenAPI Generator can be found link:https://openapi-generator.tech/[here].
For an example how to use the OpenAPI Generator, see the link:https://openapi-generator.tech/docs/usage/[OpenAPI Generator documentation].

== Questions / Issues / Contributions

If you have any questions or need help, please take a look to the https://support.weidmueller.com/support-center/[Weidmueller Support Center].

If you would like to contribute to the project, please take a look at our link:CONTRIBUTING.md[Contributing Guidelines].

== License

This project is licensed under the link:./LICENSE[MIT license].
