// SPDX-FileCopyrightText: 2025 - 2026 Weidmueller Interface GmbH & Co. KG <oss@weidmueller.com>
//
// SPDX-License-Identifier: MIT

= u-OS Data Hub - API Specifications
:toc:

The `u-os-hub-api` repository contains multiple API specifications for the u-OS Data Hub.

A general explanation of what the u-OS Data Hub is can be found link:https://support.weidmueller.com/online-documentation/latest/312416/en-GB/index.html[here].

== API Specifications

Please take a look at the Readme files of the individual API specifications for more details:

- link:openapi/README.adoc[HTTP APIs (like Variable-HTTP-API, Administration API, ..)]
- link:variable-nats-api/README.adoc[Variable-NATS-API]
- link:removable-media-update/README.adoc[Removable Media Update]
- link:task-runner/README.adoc[Task Runner]

== Version compatibility

In this repository, there is a release tag for each u-OS release.
For example, to obtain all API specifications for u-OS version 2.3, the tag `u-os-2.3` must be checked out.

Otherwise, the individual APIs adhere to link:https://semver.org/[semver].
Older specifications can therefore continue to be used if the major version of the API has not changed.

If a version is labelled `-next`, it already includes features intended for future, as yet unreleased versions of u-OS. Compatibility is not guaranteed in such cases.

== Questions / Issues / Contributions

If you have any questions or need help, please visit the link:https://support.weidmueller.com/support-center/[Weidmueller Support Center].

If you would like to contribute to the project, please take a look at our link:CONTRIBUTING.adoc[Contributing Guidelines].

== License

This project is licensed under the link:LICENSE[MIT license].
