# SPDX-FileCopyrightText: 2024 Weidmueller Interface GmbH & Co. KG <oss@weidmueller.com>
#
# SPDX-License-Identifier: CC0-1.0

version: "3"
services:
  u-os-hub-api:
    build:
      context: .
    ports:
      - 3000:3000
    command: /bin/sh -c "while sleep 1000; do :; done"
